spring:
  datasource:
    username: employee_management
    password: employee_management
    url: jdbc:mysql://localhost:3306/employee_management

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true

sql:
  init:
    mode: never